### ISSUE TITLE
Router example does not work

### ISSUE THREAD

**Issue by mikerodham** [alex-oleshkevich/vue-introjs#28]
(Y)

**Comment by wishinghand** [comment]
I know this is super old but that's because the page has a script tag that references a dist folder that is no longer there. Replace the the line that looks like this:
`<script type="text/javascript" src="../dist/index.min.js"></script>`
With this: 
`<script type="text/javascript" src="https://unpkg.com/vue-introjs@1.3.0/dist/index.min.js"></script>`
