### ISSUE TITLE
autostart doesn't work with vue-router

### ISSUE THREAD

**Issue by H0WARDDD** [alex-oleshkevich/vue-introjs#29]
I'm using 'autostart' with vue-router, but intro doesn't show after router changes, I have to refresh the whole page to show it.
I've set the 'waitTimeout' value, but it doesn't work.
vue-introjs version: 1.3.0
intro.js version: 2.9.3

**Comment by alex-oleshkevich** [comment]
Well, it is hard to implement, because the current implementation relies on page load.
In case of router, the page loaded event not fired when navigation happens so no way to determine when to start a navigation.
I suggest you to manually start introduction in the router view componet's `mounted()` hook.
