### ISSUE TITLE
Bug report: Auto start fails on second use

### ISSUE THREAD

**Issue by gabriel4649** [alex-oleshkevich/vue-introjs#7]
I start one tour on the first landing page after login. Then after that tour is over, I send the user to another page using vue-router. The tour on that second page is not started using auto start. However, if I do a refresh on that second page, the auto-tour starts as expected.

**Comment by alex-oleshkevich** [comment]
this is a correct behavior. 

if your `v-intro-autostart` is global (i.e. is in parent component of router-view), then it autostarts only once (because it's mounted only once). you need to refresh your autostart boolean model or call `this.$intro().start()` manually in your case.

or refactor your code so `v-intro-autostart` is in router-view component. then it will be mounted every time the router changes page and autostart will trigger as if page refreshed.

**Comment by gabriel4649** [comment]
Thanks! I will attempt to put v-intro-autostart in the router-view and make that work
